export const actionTypes = {
  ADD_CLASSES: "ADD_CLASSES",
  CLEAR_CLASSES: "CLEAR_CLASSES",
  ADD_SINGLE_CLASS: "ADD_SINGLE_CLASS",
  ADD_CLASSES_ERROR: "ADD_CLASSES_ERROR",
  UPDATE_SINGLE_CLASS: "UPDATE_SINGLE_CLASS",
  DELETE_SINGLE_CLASS: "DELETE_SINGLE_CLASS",
  CLEAR_CLASSES_ERROR: "CLEAR_CLASSES_ERROR",

  ADD_STUDENTS: "ADD_STUDENTS",
  CLEAR_STUDENTS: "CLEAR_STUDENTS",
  ADD_SINGLE_STUDENT: "ADD_SINGLE_STUDENT",
  ADD_STUDENTS_ERROR: "ADD_STUDENTS_ERROR",
  CLEAR_STUDENTS_ERROR: "CLEAR_STUDENTS_ERROR",
  UPDATE_SINGLE_STUDENT: "UPDATE_SINGLE_STUDENT",
  DELETE_SINGLE_STUDENT: "DELETE_SINGLE_STUDENT",
  
  ADD_COURSES: "ADD_COURSES",
  CLEAR_COURSES: "CLEAR_COURSES",
  ADD_SINGLE_COURSE: "ADD_SINGLE_COURSE",
  UPDATE_SINGLE_COURSE: "UPDATE_SINGLE_COURSE",
  DELETE_SINGLE_COURSE: "DELETE_SINGLE_COURSE",
  ADD_COURSES_ERROR: "ADD_COURSES_ERROR",
  CLEAR_COURSES_ERROR: "CLEAR_COURSES_ERROR",
  
}